# Generated by Django 4.2.1 on 2023-06-12 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patient_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("city", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("blood_type", models.CharField(max_length=10)),
                ("actual_estimation", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("age", models.IntegerField()),
                (
                    "sex",
                    models.CharField(choices=[("0", "0"), ("1", "1")], max_length=2),
                ),
                ("weight", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "diabetes",
                    models.CharField(choices=[("0", "0"), ("1", "1")], max_length=2),
                ),
                ("systolic", models.FloatField()),
                ("diastolic", models.FloatField()),
                ("cholesterol", models.IntegerField()),
                ("hdl", models.FloatField()),
                ("ldl", models.FloatField()),
                ("triglycerides", models.IntegerField()),
                (
                    "smoking",
                    models.CharField(choices=[("0", "0"), ("1", "1")], max_length=2),
                ),
                (
                    "background",
                    models.CharField(choices=[("0", "0"), ("1", "1")], max_length=2),
                ),
                ("estimation", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("id", models.CharField(max_length=30)),
                ("id_type", models.CharField(max_length=10)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("cellphone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Results_Medic_Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppBack.patient",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppBack.results",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AppBack.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor_Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppBack.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AppBack.user"
                    ),
                ),
            ],
        ),
    ]
