# Generated by Django 4.2.1 on 2023-05-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Medico', 'Medico')], max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('blood_type', models.CharField(max_length=10)),
                ('actual_estimation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=2)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('diabetes', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=2)),
                ('systolic', models.FloatField()),
                ('diastolic', models.FloatField()),
                ('cholesterol', models.IntegerField()),
                ('hdl', models.FloatField()),
                ('ldl', models.FloatField()),
                ('triglycerides', models.IntegerField()),
                ('smoking', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=2)),
                ('background', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=2)),
                ('estimation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppBack.account')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Medico', 'Medico')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Results_Medic_Matient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBack.patient')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBack.results')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBack.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBack.patient')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBack.user')),
            ],
        ),
    ]
