# Generated by Django 4.2.1 on 2023-06-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppBack", "0003_remove_user_is_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="cellphone",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
