# Generated by Django 4.2.1 on 2023-06-29 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppBack", "0005_rename_results_medic_patient_resultsmedicpatient"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Doctor_Patient",
            new_name="MedicPatient",
        ),
    ]
